version: '3'
services:
  payment-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env

  stripe-cli:
    image: stripe/stripe-cli:latest
    command: listen --api-key sk_test_51PZuqp2LM7f5OcY9hZbAcpHvNqZ0ss71Ral8ExxTqLdfvrL5yhpiJA28urmfAleFgBHGpQA66Eiqw9N2buB87yoi001TZQOS3s --forward-to http://host.docker.internal:3000/webhook --device-name pc-local-w
    network_mode: host

networks:
  mynetwork:
    driver: bridge
